steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build app2'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app-2'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push Docker Image for app2'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app-2'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Delete existing resources'
  args:
    - 'delete'
    - '-f'
    - 'deployment.yaml'
    - '--ignore-not-found'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy app2'
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster'

options:
  logging: CLOUD_LOGGING_ONLY